name: Build and Deploy to K3s

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t flask-k3s-demo:latest .

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag flask-k3s-demo:latest ${{ secrets.DOCKER_USERNAME }}/flask-k3s-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-k3s-demo:latest

  deploy:
    runs-on: self-hosted  # Your K3s host must be connected as GitHub Runner
    needs: build
    steps:
      - name: Deploy to K3s
        run: |
          kubectl set image deployment/flask-deployment flask-container=${{ secrets.DOCKER_USERNAME }}/flask-k3s-demo:latest
